import { SEOHead } from "@/components/SEOHead";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import PageTransition from "@/components/PageTransition";

const TermsOfService = () => {
  return (
    <PageTransition>
      <SEOHead
        title="Terms of Service"
        description="Read the Terms of Service for AiAgeCalc.com. Understand the rules, disclaimers, and conditions for using our free AI-powered age calculators and birthday tools."
        type="website"
      />
      <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
        <main className="container mx-auto px-4 py-12">
          <div className="max-w-4xl mx-auto">
            <Card className="border-2">
              <CardHeader className="text-center pb-6">
                <CardTitle className="text-4xl font-bold text-foreground">Terms of Service</CardTitle>
                <p className="text-muted-foreground mt-2">Last updated: February 2026</p>
              </CardHeader>
              <CardContent className="prose dark:prose-invert max-w-none space-y-6 text-foreground/90">

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">1. Acceptance of Terms</h2>
                  <p>
                    By accessing and using AiAgeCalc.com ("the Site"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website. These terms apply to all visitors, users, and others who access the Site.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">2. Description of Services</h2>
                  <p>
                    AiAgeCalc.com provides free, AI-powered tools and calculators related to age, birthdays, and celebrations. Our services include but are not limited to: age calculators, planetary age converters, celebrity birthday databases, AI face age detection, compatibility calculators, life expectancy estimators, pet age calculators, due date calculators, and AI-generated greeting cards. All tools are provided for informational and entertainment purposes only.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">3. Disclaimers</h2>
                  <p>
                    <strong>Health & Medical Information:</strong> Our health score calculator, life expectancy estimator, and due date calculator are for entertainment and general informational purposes only. They do not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for medical decisions.
                  </p>
                  <p>
                    <strong>AI-Generated Content:</strong> Content generated by our AI tools (including greetings, compatibility scores, past life readings, and celebrity profiles) is generated by artificial intelligence and should be treated as entertainment. We do not guarantee the accuracy, completeness, or reliability of AI-generated content.
                  </p>
                  <p>
                    <strong>Financial Information:</strong> Our retirement calculator provides estimates based on general assumptions and should not be considered financial advice. Consult a financial advisor for actual retirement planning.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">4. Intellectual Property</h2>
                  <p>
                    All content on AiAgeCalc.com, including text, graphics, logos, icons, images, and software, is the property of AiAgeCalc.com or its content suppliers and is protected by international copyright laws. You may not reproduce, distribute, modify, or create derivative works from any content on this Site without our prior written consent.
                  </p>
                  <p>
                    Celebrity images used on this Site are sourced from publicly available databases and are used under fair use for informational purposes. All celebrity names and likenesses remain the property of their respective owners.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">5. User Conduct</h2>
                  <p>When using our Site, you agree not to:</p>
                  <ul className="list-disc list-inside space-y-1">
                    <li>Use the Site for any unlawful purpose or in violation of any applicable laws</li>
                    <li>Upload harmful, offensive, or inappropriate content through any of our tools</li>
                    <li>Attempt to interfere with the proper functioning of the Site</li>
                    <li>Use automated tools to scrape, crawl, or extract data from the Site without permission</li>
                    <li>Impersonate any person or entity when using our services</li>
                    <li>Upload images of minors or any non-consensual photos to our AI face detection tools</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">6. Privacy & Data</h2>
                  <p>
                    Your use of our Site is also governed by our Privacy Policy. Photos uploaded to our AI face age detector and look-alike finder are processed in real time and are not stored on our servers. We do not collect personally identifiable information unless you voluntarily provide it through our contact form.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">7. Limitation of Liability</h2>
                  <p>
                    AiAgeCalc.com and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of the Site or any of its tools. This includes but is not limited to damages for errors, omissions, interruptions, defects, delays, or any other performance issues. The Site and all its tools are provided on an "as is" and "as available" basis without warranties of any kind.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">8. Third-Party Links & Advertising</h2>
                  <p>
                    Our Site may contain links to third-party websites and display advertisements served by third-party ad networks (including Google AdSense). We are not responsible for the content, privacy practices, or terms of any third-party sites. Clicking on advertisements or third-party links is at your own risk.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">9. Changes to Terms</h2>
                  <p>
                    We reserve the right to update or modify these Terms of Service at any time without prior notice. Changes become effective immediately upon posting on this page. Your continued use of the Site after changes are posted constitutes your acceptance of the revised terms.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold text-foreground">10. Contact</h2>
                  <p>
                    If you have any questions about these Terms of Service, please contact us through our website's contact form or email us at the address provided on our Contact page.
                  </p>
                </section>

              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </PageTransition>
  );
};

export default TermsOfService;
